### ISSUE TITLE
Add a way to limit the amount of rate limit requests per guild, to avoid being IP-banned.

### ISSUE THREAD

**Issue by promise** [countr/countr#106]
# Feature request

Add a way to limit the amount of rate limit requests per guild, to avoid being IP-banned. When limit has been reached, disable the counting channel for an hour or something.

Reason why this might get implemented is because if 10,000 invalid/bad requests (4xx status codes) were made to Discord within 10 minutes then the whole server (including other projects on it) will get temporarily IP-banned. That is 16.66 invalid/bad requests per second, shared on the entire server. Countr in production is currently being hit with one bad request per second, so we're far from the average required. But the server has actually been temporarily ip-banned from Discord before, because of Countr, so I would like to maybe at least optimize this.

Premium will bypass this probably as Premium users have paid for it and won't really abuse something they've paid for.

The main reason why rate limits occur on Countr at the moment is the reposting-modules. Not all servers use these, but we should still consider optimizing it for the future.

**Comment by wrac4242** [comment]
any ideas how this could be done?

**Comment by MaSeraphina** [comment]
There is a bot that does this with some sort of a activity score.
Every server starts at 0, for every big action that happens the score goes up by 1 or 2. When you reach a score 20 a message is sent in a preset channel that some features are reduced/disabled for some time. (e.g. /level displays the level as text instead of a picture)
Every 5-7 minutes the score drops by 2-4 points until its below a certain level.

![image](https://user-images.githubusercontent.com/81922575/194708402-c1e39311-de8b-4f4d-abd6-fc2fc6a80b2b.png)

**Comment by wrac4242** [comment]
that would work yea, however the issue could be stuff like "send message in a channel" and the bot not having access to the channel, plus the sorta timing relating stuff can get messy. but that method seems practical

**Comment by promise** [comment]
This was mostly an issue when doing notifications and people intentionally blocking the bot to get it IP-banned. It's fixed now though so should be fine to ignore this.
