### ISSUE TITLE
make this a template repository

### ISSUE THREAD

**Issue by FrozenHyper** [countr/countr#132]
# Feature request

Write a summary here. It can be as short as the short summary in the title, or longer.

Make this a template repository so that we can make it a private repo.

**Comment by promise** [comment]
why would you need a private repo?

**Comment by promise** [comment]
closing due to no response. if you need a private repo then follow [this guide](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/duplicating-a-repository) or just copy/paste the files in your own private repo. I'm not going to make this a template just for one user.
