### ISSUE TITLE
[BOT] c!top value error

### ISSUE THREAD

**Issue by hemangsrr** [countr/countr#15]
# Bug

The c!top gives the wrong count for users. Those with more than 100 counts are shown as 52, and so on.

## Reproducing

1. Run command 'c!top'
2. Then search for messages from a user in the counting channel
3. Compare  the count values

## Expected behavior

Both should be the same

## Screenshots

![aimie counting](https://user-images.githubusercontent.com/44643029/71823871-494e2900-30be-11ea-87e7-daec3e4d9c1a.PNG)
![c!top](https://user-images.githubusercontent.com/44643029/71823872-494e2900-30be-11ea-99fa-d2fbf7ce66ad.PNG)

**Comment by promise** [comment]
Your issue is not a bug but rather intended: the amount of counts from each user in the counting channel is not directly linked up to the score of said user. The scoring system isn't linked with the number of counts the user has, but rather that when you count a number, your score increases by one.

This is not a bug, but I can look if there is a possibility of detecting scores with a command, meaning the bot will go through all the messages in the counting channel and then send a JSON back. See #16.

Note: because of the database issues we had earlier this week, the scores might have been set back. This might be the cause of why the scores are inaccurate.

**Comment by hemangsrr** [comment]
that is what i meant. As we have been using countr from the begininng.  So both the counts should have been the same. It might be the database issue tho
