### ISSUE TITLE
extra flows

### ISSUE THREAD

**Issue by dylanamic** [countr/countr#54]
Hey, so I think something that you should allow on countr is that we could purchase more flows, just flows. Currently your patreons increase everything, but it'll be nice if there's something that will just increase the number of flows. Previously before this update, I used to have roles given out to users for every 1k score, but now with the limited number of flows, I can no longer do that. But I don't need more triggers per flow as it's just the 1 trigger. So maybe something that can be purchased separately, or different patreon plans to add different amounts for flows?

**Comment by promise** [comment]
Hey. We don't plan on increasing the limit in the near future. If you'd like, you can always self-host the bot and increase the limit yourself. The limit is there because every time someone counts a successful count, Countr must run additional code per flow to check if the flow is triggered or not, and additionally run the flow actions if it got triggered. The limit is mostly there to save CPU usage.

Premium is on a different cluster and has its own CPU time, therefore we've increased the limits on Premium. We might increase the limits on Premium even further though.
