### ISSUE TITLE
the bot gets confused when editing (Bug)

### ISSUE THREAD

**Issue by Agent-Noob** [countr/countr#632]
So when you write a number and try to edit the message gets deleted but when you write and then send someone else, you can edit and then the bot gets confused. we were at 13596 and it jumped down to 12456

**Comment by promise** [comment]
CNR, sounds like something else is the underlying issue to your problem here. The bot will keep its count upon editing a count, however if someone edits a message then there's nothing Countr can do to stop them. However, by using modules that repost the count, users will be unable to edit their counts. If it's the last count, Countr will repost either way to keep the count. But if someone else has the last count then Countr will ignore it.
