### ISSUE TITLE
[BUG] not starting

### ISSUE THREAD

**Issue by djohts** [countr/countr#86]
# Bug Report

Countr doesn't start on last commit

## Reproducing

1. Update your files like in last commit (reload cmd)
2. Start your bot

## Expected behavior

No errors, working reload command but got `Manager: Shard X is starting.` msg and after 10-15 seconds it says `Killed`

## Screenshots

![image](https://user-images.githubusercontent.com/68508885/110814324-02dff580-8292-11eb-8d21-c2016f8303f9.png)

**Comment by promise** [comment]
Cannot reproduce. A quick google search says it might be because of your RAM. Make sure you've updated all the files and not just the reload command as well. Also try and run the bot locally to see if it's an issue with your hosting provider or the actual source code itself. Get back to me when you know more about the issue.

**Comment by fabianneufang** [comment]
I cannot reproduce it either.

**Comment by djohts** [comment]
this bug was fixed in commit ec302841ffcedeebecf988eadf847e8adcb81a8b, thanks btw

**Comment by promise** [comment]
seems to be a non-Windows bug as testing on Windows worked fine. Hence why I couldn't reproduce
