### ISSUE TITLE
Use a separate webhook server for slash commands?

### ISSUE THREAD

**Issue by promise** [countr/countr#98]
# Feature request

Use a separate webhook server for slash commands. Discord supports sending interaction events over webhooks, we could potentially just use that instead of doing it over the websocket.

**Pros:**
- it works even if the bot is offline, which might be useful in telling the user "hey, the bot is offline" or "hey, the bot is starting up, eta is xxx" etc.
- we can fetch information directly from the database, not relying on a cache or anything like that.
- we can have a debug command telling people why it is offline, perhaps the shard is dead or the shard is starting up and won't respond just yet etc.
- the main bot won't get performance issues by it, even though that doesn't really matter a whole lot.
- we can have the same server setup for Countr and Countr Premium as it's just responding to the webhook request Discord sends, it doesn't need a token or anything like that.

**Cons:**
- writing to the database won't really be possible as we local cache all the guild data. If we extend slash commands in the future (which I doubt we will), we won't be able to update the local database unless we somehow make extra code to account for that.

Would like to hear some ideas from you guys about this.

**Comment by Ta1al** [comment]
The local mongodb can be opened for external connections. [This](https://www.digitalocean.com/community/tutorials/how-to-configure-remote-access-for-mongodb-on-ubuntu-20-04) or [this](https://medium.com/founding-ithaka/setting-up-and-connecting-to-a-remote-mongodb-database-5df754a4da89) should help.

You can also host the slash commands webserver on the same host as the bot, so the local database can be used by both of them.

Alternatively, we can use monodb Atlas (i.e., a remote database), since countr already has a caching system.

**Comment by promise** [comment]
If we cache stuff then it won't update. And since we use shards, the local cache is not the same. The bot basically creates 69 local caches (because we have 69 shards).

Opening up 69 connections through the bot that can be accessed either publicly or through another process on the server, will be tricky and inefficient for the future.

Even if we host the webserver on the same host/process, the cache will be different and there's no point in doing this instead of a webserver elsewhere. We might as well just use the current method instead.

**Comment by promise** [comment]
Closing this as we will use components and stuff, which would be better to have in the same code as the original bot and not separated.
